"""
Django settings for mcmProject project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 저장소 루트(.env)를 로드 — backend/mcmProject가 아니라 리포지토리 최상단에 .env가 있음
load_dotenv(BASE_DIR.parent.parent / ".env")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 예전엔 여기 실제 키 값이 그대로 하드코딩돼서 git에 커밋돼 있었음 -> .env로 이동.
# .env에 DJANGO_SECRET_KEY가 없으면(팀원이 아직 .env를 안 채운 경우 등) 개발용으로만
# 쓰는 placeholder로 대체 — 이 fallback 값은 절대 실제 배포에 쓰면 안 됨.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-CHANGE-ME-in-dotenv-local-dev-only",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 개발용 설정 — 로컬 네트워크(휴대폰 QR 테스트 등)에서 어떤 호스트로 접속해도 허용.
# DEBUG=True인 동안만 쓰는 값이라 지금은 괜찮지만, 실제 배포 시에는 실제 도메인/IP로 좁혀야 함.
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'accounts',
    'onboarding',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CorsMiddleware는 CommonMiddleware보다 먼저 와야 함 (django-cors-headers 공식 권장 순서)
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ---- React 프론트(별도 오리진)에서 세션 쿠키 기반으로 API를 호출하기 위한 CORS/CSRF 설정 ----
# 프론트 개발 서버 주소는 팀마다/도구마다(Vite=5173, CRA=3000) 다를 수 있어서 .env의
# FRONTEND_ORIGINS(콤마로 구분)로 오버라이드할 수 있게 하고, 지정 안 하면 흔한 기본값들을 허용.
_default_frontend_origins = (
    "http://localhost:3000,http://127.0.0.1:3000,"
    "http://localhost:5173,http://127.0.0.1:5173"
)
FRONTEND_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("FRONTEND_ORIGINS", _default_frontend_origins).split(",")
    if origin.strip()
]

CORS_ALLOWED_ORIGINS = FRONTEND_ORIGINS
# 세션 쿠키(로그인 상태)를 프론트에서 fetch(..., {credentials: 'include'})로 주고받으려면 필요
CORS_ALLOW_CREDENTIALS = True

# CSRF 쿠키/토큰 검증도 별도 오리진 요청을 신뢰하도록 같은 목록을 등록해야 함
# (안 하면 로그인 등 POST 요청이 전부 403 CSRF 오류로 막힘)
CSRF_TRUSTED_ORIGINS = FRONTEND_ORIGINS

ROOT_URLCONF = 'mcmProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mcmProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # 시대별 이미지를 백그라운드에서 동시에 미리 생성하다 보니 쓰기가 겹칠 수 있음 —
        # SQLite는 동시 쓰기를 하나만 허용해서, 기본 타임아웃(5초)보다 넉넉하게 잡아
        # "database is locked" 에러 대신 잠깐 대기 후 처리되게 함
        'OPTIONS': {
            'timeout': 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'accounts.User'

# 기본값(/accounts/profile/)은 존재하지 않는 URL이라 로그인 직후 404가 남 -> 명시적으로 지정
LOGIN_REDIRECT_URL = 'shop:select_bag'
LOGIN_URL = 'login'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'