"""
Django settings for mcmProject project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 저장소 루트(.env)를 로드 — backend/mcmProject가 아니라 리포지토리 최상단에 .env가 있음
load_dotenv(BASE_DIR.parent.parent / ".env")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 예전엔 여기 실제 키 값이 그대로 하드코딩돼서 git에 커밋돼 있었음 -> .env로 이동.
# .env에 DJANGO_SECRET_KEY가 없으면(팀원이 아직 .env를 안 채운 경우 등) 개발용으로만
# 쓰는 placeholder로 대체 — 이 fallback 값은 절대 실제 배포에 쓰면 안 됨.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-CHANGE-ME-in-dotenv-local-dev-only",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 개발용 설정 — 로컬 네트워크(휴대폰 QR 테스트 등)에서 어떤 호스트로 접속해도 허용.
# DEBUG=True인 동안만 쓰는 값이라 지금은 괜찮지만, 실제 배포 시에는 실제 도메인/IP로 좁혀야 함.
ALLOWED_HOSTS = ['*']

# React(Vite) 개발 서버가 /api, /shop 등을 이 서버로 프록시(changeOrigin)하기 때문에
# Django가 보는 Host는 이 서버 자신이 되지만, 브라우저가 보내는 Origin 헤더는
# 여전히 localhost:5173이라 CSRF의 Origin 검사가 실패한다 -> 신뢰 origin으로 등록.
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'onboarding',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mcmProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mcmProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # 시대별 이미지를 백그라운드에서 동시에 미리 생성하다 보니 쓰기가 겹칠 수 있음 —
        # SQLite는 동시 쓰기를 하나만 허용해서, 기본 타임아웃(5초)보다 넉넉하게 잡아
        # "database is locked" 에러 대신 잠깐 대기 후 처리되게 함
        'OPTIONS': {
            'timeout': 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

AUTH_USER_MODEL = 'accounts.User'

# 기본값(/accounts/profile/)은 존재하지 않는 URL이라 로그인 직후 404가 남 -> 명시적으로 지정
LOGIN_REDIRECT_URL = 'shop:select_bag'
LOGIN_URL = 'login'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
