# Generated by Django 6.1 on 2026-08-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='captured_photos/')),
                ('is_chosen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_photos', to='shop.personaselection')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
