# Generated by Django 6.1 on 2026-08-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_capturedphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, related_name='recommended_by', to='shop.product'),
        ),
    ]
