# Generated by Django 6.1 on 2026-08-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_erareference_face_height_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='색깔'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_info',
            field=models.TextField(blank=True, verbose_name='상세정보'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.TextField(blank=True, verbose_name='특성'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='상품코드'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='크기'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='사진'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='가격'),
        ),
    ]
